INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('1', 'Star Metal Pickaxe', '51020', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('1', 'Star Metal Cleaver', '41030', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('1', 'Star Metal Sickle', '51042', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('1', 'Star Metal Butcher Knife', '51312', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('1', 'Bearer Pack', '52080', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('1', 'Medium Hardness High Grade', '91006', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('1', 'Medium Guantlets High Grade', '91007', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('1', 'Medium Tasset High Grade', '91008', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('1', 'Medium Boots High Grade', '91009', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('2', 'Steel Truncheon', '51307', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('2', 'Leather Bindings', '51963', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('3', 'Hunters Potion', '18305', '5');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('3', 'Elixir of Grace', '18290', '5');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('3', 'Elixir of Numbing', '18292', '5');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('3', 'Elixir of Enduring', '18295', '5');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('3', 'Elixir of Might', '18297', '5');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('3', 'Elixir of Ingestion', '18298', '5');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('3', 'Elixor of Vigor', '18299', '5');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('3', 'Elixor of Freedom', '18304', '5');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('4', 'Brown Horse', '92232', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('4', 'Scout Saddle', '2706', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('5', 'Oil of Agony', '92178', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('5', 'Oil of Penetration', '92179', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('5', 'Oil of Balance', '92180', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('5', 'Oil of Concussion', '92181', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('5', 'Oil of Bounty', '92182', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('6', 'White Dye', '17115', '50');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('6', 'Black Dye', '17116', '50');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('6', 'Full Green Dye', '17117', '50');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('6', 'Full Blue Dye', '17125', '50');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('6', 'Full Yellow Dye', '17127', '50');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('6', 'Full Purple Dye', '17132', '50');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('6', 'Blood Red Dye', '17137', '50');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('6', 'Royal Purple Dye', '17134', '50');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('6', 'Pure Orange Dye', '17138', '50');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('6', 'Deep Sea Green', '17118', '50');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('7', 'Redeemed Legion Pauldron', '91321', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('7', 'Redeemed Legion Helmet', '91320', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('7', 'Redeemed Legion Gauntlets', '91322', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('7', 'Redeemed Legion Tasset', '91323', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('7', 'Redeemed Legion Boots', '91324', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('7', 'Star Metal Pickaxe', '51020', '1');
INSERT INTO shop_kits (kitId, kitname, itemId, itemcount) VALUES ('7', 'Spiced Haunch', '18217', '50');